on:
  push:
    branches:
      - master

name: booklet

jobs:
  bookdown:
    name: build-bookdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install tinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install system dependencies
        run: |
          sudo apt install -y curl libcurl4-doc libcurl4-openssl-dev

      - name: Install R dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::local_package_deps(dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ runner.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Install book dependencies
        run: |
          remotes::install_github("rstudio/bookdown")
          remotes::install_github("rstudio/bslib")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Render book
        run: |
          Rscript -e 'bookdown::clean_book(TRUE)'
          Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from https://github.com/Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: _book                      # optional
          # Destination path
          path: _book                      # optional

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          # https://github.com/settings/tokens
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ${{ secrets.EMAIL }}      # must be a verified email
          build_dir: _book/                # "_site/" by default
